export class Enrollment {
  constructor(data = {}) {
    // System fields
    this.id = data.id || null;
    this.documentId = data.documentId || null;

    // Relations (matching schema)
    this.student = data.student || null;
    this.academicYear = data.academicYear || data.academic_year || null;
    this.class = data.class || null;
    this.administration = data.administration || null;

    // Core fields from schema
    this.grNo = data.grNo || data.gr_no || '';  // Maps to gr_no in schema
    this.dateEnrolled = data.dateEnrolled || data.date_enrolled || new Date().toISOString();  // Maps to date_enrolled
    this.enrollmentStatus = data.enrollmentStatus || data.enrollment_status || 'Enquiry';  // Maps to enrollment_status enum
    this.admissionType = data.admissionType || data.admission_type || '';  // Maps to admission_type enum
    this.lcReceived = data.lcReceived || data.lc_received || false;  // Maps to lc_received
    this.paymentPreference = data.paymentPreference || data.payment_preference || 'installments';  // Maps to payment_preference

    // Timestamps (auto-generated by Strapi)
    this.createdAt = data.createdAt || null;
    this.updatedAt = data.updatedAt || null;
  }

  get isCurrentYear() {
    if (!this.academicYear) return false;
    const currentYear = new Date().getFullYear();
    return this.academicYear.year === currentYear;
  }

  get className() {
    return this.class?.className || '';
  }

  get division() {
    // Division comes from administration relationship
    return this.administration?.division || null;
  }

  get divisionName() {
    return this.administration?.division?.divisionName || this.administration?.division?.name || '';
  }

  get studentName() {
    if (this.student) {
      return `${this.student.first_name || ''} ${this.student.last_name || ''}`.trim();
    }
    return '';
  }

  isEnrolled() {
    return this.enrollmentStatus === 'Enrolled';
  }

  isWaiting() {
    return this.enrollmentStatus === 'Waiting';
  }

  isRejected() {
    return this.enrollmentStatus === 'Rejected';
  }

  isEnquiry() {
    return this.enrollmentStatus === 'Enquiry';
  }

  isProcessing() {
    return this.enrollmentStatus === 'Processing';
  }

  toJSON() {
    return {
      id: this.id,
      documentId: this.documentId,
      student: this.student,
      academicYear: this.academicYear,
      class: this.class,
      administration: this.administration,
      grNo: this.grNo,
      dateEnrolled: this.dateEnrolled,
      enrollmentStatus: this.enrollmentStatus,
      admissionType: this.admissionType,
      lcReceived: this.lcReceived,
      paymentPreference: this.paymentPreference,
      // Computed properties
      division: this.division,
      className: this.className,
      divisionName: this.divisionName,
      studentName: this.studentName,
      isCurrentYear: this.isCurrentYear,
      createdAt: this.createdAt,
      updatedAt: this.updatedAt
    };
  }
}